[package]
name = "chipioindustries/pounce"
description = "Multiplayer solitaire"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
LeakyBucket = "chipioindustries/leaky-bucket@1.0.1"
Llama = "chipioindustries/llama@1.2.2"
Roact = "roblox/roact@1.4.2"
RoactRodux = "roblox/roact-rodux@0.3.0"
Remotes = "chipioindustries/remotes@1.0.1"
ReplicationMiddleware = "chipioindustries/replication-middleware@1.0.0"
Rodux = "chipioindustries/rodux@3.0.4"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"