[package]
name = "chipioindustries/pounce"
description = "Multiplayer solitaire"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
Rodux = "chipioindustries/rodux@3.0.4"
ReplicationMiddleware = "chipioindustries/replication-middleware@1.0.0"
RoactRodux = "roblox/roact-rodux@0.3.0"
Llama = "chipioindustries/llama@1.2.2"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"